import { BestAppsComponentFixture } from '../../helpers/Component';

const fixture = new BestAppsComponentFixture('/tests/fixtures/bestapps-component.html', '#component1');

describe('BestAppsComponent', () => {
    before(() => fixture.open());

    fixture.testBestAppsBase();

    it('should generate unique guids per instance', async () => {
        const f2 = new BestAppsComponentFixture('/tests/fixtures/bestapps-component.html', '#component2');
        const guid1 = await fixture.guid();
        const guid2 = await f2.guid();
        expect(guid1).not.toBe(guid2);
    });

    it('should enable debug option via attribute', async () => {
        const debugFixture = new BestAppsComponentFixture('/tests/fixtures/bestapps-component.html', '#debug-component');
        expect(await debugFixture.isDebug()).toBe(true);
    });

    it('should support pub/sub messaging', async () => {
        const received = await fixture.subscribePubSub<{ v: number }>('test-evt', { v: 42 });
        expect(received.v).toBe(42);
    });

    it('should remove subscribeOnce handler after first call', async () => {
        expect(await fixture.subscribeOnceCount('once-test', 3)).toBe(1);
    });

    it('should create components dynamically', async () => {
        const dyn = await fixture.createDynamic('ba-component', 'dynamic1', 'container');
        const guid = await dyn.guid();
        expect(guid).toBeTruthy();
        expect(guid!.length).toBe(12);
    });
});

describe('BestAppsComponent — applyCustomStyles', () => {
    const styled = new BestAppsComponentFixture('/tests/fixtures/bestapps-component.html', '#component2');
    before(() => styled.open());

    it('should apply Tailwind utility classes to the wrapper', async () => {
        await styled.applyCustomStyles('p-4 opacity-50');
        const classes = await styled.wrapperClasses();
        expect(classes).toContain('p-4');
        expect(classes).toContain('opacity-50');
        // utility CSS is generated by BestAppsStyleEngine into the shared adopted sheet
        const pad = await styled.wrapperStyle('padding-left');
        expect(parseFloat(pad)).toBeGreaterThan(0);
    });

    it('should remove previously applied classes when className is cleared', async () => {
        await styled.applyCustomStyles('p-4');
        await styled.applyCustomStyles();
        expect(await styled.wrapperClasses()).not.toContain('p-4');
    });

    it('should apply raw CSS declarations inline to the wrapper', async () => {
        await styled.applyCustomStyles(undefined, 'outline: 2px dashed red; opacity: 0.5');
        expect(await styled.wrapperInlineStyle('opacity')).toBe('0.5');
        expect(await styled.wrapperInlineStyle('outline')).toContain('dashed');
    });

    it('should clear previously applied raw declarations on update', async () => {
        await styled.applyCustomStyles(undefined, 'opacity: 0.5');
        await styled.applyCustomStyles();
        expect(await styled.wrapperInlineStyle('opacity')).toBe('');
    });
});
